### ISSUE TITLE
WARNING: make_standalone_toolchain.py is no longer necessary

### ISSUE THREAD

**Issue by hannesa2** [ravinderjangra/AndroidResumeIssue#1]
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/3314607/79536948-7f1d8900-8081-11ea-99a0-b1733ccb2c5c.png">

Will this become an issue in the future ?
I guess yes, that's why it should be solved anyhow

**Comment by ravinderjangra** [comment]
yes, this may cause an issue in the future. This action helps in creating a new toolchain for the build but the new changes in the NDK we don't require to build a new toolchain but we can use the existing pre-build one shipped in the NDK itself.
